from db.connection import get_db, get_cursor, close_pool
from db.queries import (
    get_user,
    create_user,
    update_user_goals,
    fetch_goals,
    save_food_log,
    save_food_logs_bulk,
    fetch_today_logs,
    fetch_logs_range,
    update_food_log,
    delete_food_log,
    fetch_daily_total,
    fetch_weekly_summary,
    fetch_streak,
    update_streak,
    image_hash,
    get_cached_image,
    save_image_cache,
)
